### ISSUE TITLE
fit.climate.reponse bug NA

### ISSUE THREAD

**Issue by reverdya** [guillaumeevin/QUALYPSO#6]
In fit.climate.response

varInterVariability = mean(apply(etaStar,2,var),na.rm=T)

should be replaced by

varInterVariability = mean(apply(etaStar,2,var,na.rm=T),na.rm=T)

to allow for NA in climate responses sucha as for example when the starting date varies with the chain

**Comment by reverdya** [comment]
With this weirdly it seem that varInterVariability disappeared from QUALYPSOOUT$CLIMATEESPONSE along with climateResponse while QUALYPSOOUT$INTERNALVAR is still there

**Comment by guillaumeevin** [comment]
I have inserted the first modification:

varInterVariability = mean(apply(etaStar,2,var,na.rm=T),na.rm=T)

Concerning the second comment varInterVariability is not in CLIMATEESPONSE field of the final object, this is correct.
